// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAofnbabRrjBol4LWYI45sZ65DTjYTQx-A',
    appId: '1:1065859123513:web:80fe7c46ce362fdacf00e8',
    messagingSenderId: '1065859123513',
    projectId: 'flamescope-a1274',
    authDomain: 'flamescope-a1274.firebaseapp.com',
    storageBucket: 'flamescope-a1274.firebasestorage.app',
    measurementId: 'G-6WD2N7RDW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPmIITxCGtaIY1ckaIqlT_B74tCVdeUo',
    appId: '1:1065859123513:android:416dcbdf8b001cdccf00e8',
    messagingSenderId: '1065859123513',
    projectId: 'flamescope-a1274',
    storageBucket: 'flamescope-a1274.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAofnbabRrjBol4LWYI45sZ65DTjYTQx-A',
    appId: '1:1065859123513:web:b7ed00d3f09584c5cf00e8',
    messagingSenderId: '1065859123513',
    projectId: 'flamescope-a1274',
    authDomain: 'flamescope-a1274.firebaseapp.com',
    storageBucket: 'flamescope-a1274.firebasestorage.app',
    measurementId: 'G-SBT74NRGZP',
  );
}
